esy/pesy

- .ci/build.yaml
- README.md
This should turn the CI green and let us experiment the new ideas.
> CI: Fix workingDirectory for the new project

- assets/pesy-package.template.json
- bin/Pesy.re
- e2e-tests/pesy-configure-test-projects/pesy-c-stubs/package.json
- e2e-tests/pesy-configure-test-projects/pesy-flags/package.json
- e2e-tests/pesy-configure-test-projects/pesy-modes/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-lib-entry/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-relative/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-scoped/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-lwt-sample/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm/package.json
- e2e-tests/pesy-configure-test-projects/pesy-preprocess/package.json
- e2e-tests/pesy-configure-test-projects/pesy-virtual/package.json
- e2e-tests/pesy-configure-test-projects/raw/package.json
- library/FieldTypes.re
- library/JSON.re
- library/JSON.rei
- library/PesyConf.re
- library/PesyConf.rei
TODO: accept only `.re` file as a string like npm.
```json
{
"bin": "App.re"
}
```
> 'bin' property is now a json

- assets/pesy-Test.template.re
- assets/pesy-package.template.json
- e2e-tests/TestBootstrapper.re
- e2e-tests/pesy-configure-test-projects/pesy-c-stubs/package.json
- e2e-tests/pesy-configure-test-projects/pesy-flags/package.json
- e2e-tests/pesy-configure-test-projects/pesy-modes/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-lib-entry/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-relative/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-scoped/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-lwt-sample/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm/package.json
- e2e-tests/pesy-configure-test-projects/pesy-preprocess/package.json
- e2e-tests/pesy-configure-test-projects/raw/package.json
- library/Executable.re
- library/Executable.rei
- library/Library.re
- library/Library.rei
- library/PesyConf.re
- library/Test.re
- library/Test.rei
> Uses (test ...) stanza for a test subpackage

- .ci/utils/restore-build-cache.yml
CI setup, courtesy of @ulrikstrid Thank you, Ulrik!
Rest API workaround for download artifacts, courtesy of @jordwalke
> Use Rest API to download and restore the cache.

- .ci/checksum.js
- .gitignore
- bin/Pesy.re
- e2e-tests/Runner.re
- package.json
- scripts/verdaccio.yaml
Minor fix to previous deployment (npmrc)
> Bump to v0.5.0-alpha.3

- README.md
> Updating docs for 0.5.0

- README.md
Same issue as in [jordwalke/pesy](https://github.com/jordwalke/pesy/pull/19/)
> Fix markdown code issue with true|false

- npm-cli/src/Pesy.bs.js
- npm-cli/src/Pesy.re
Template repo now has a separate README meant for the repo itself
> Use README-template.md as README template

- README.md
- bin/Pesy.re
- bin/dune
- e2e-tests/TestPesyConfigure.re
- package.json
> Adds ls-libs to help user specify the correct require path

- .ci/build-platform.yml
- .ci/use-calc-esy-install-path.yml
- azure-pipelines.yml
> Use calculated esy install path (inspired by reason repo)

- lib/Common.re
- lib/PesyModule.re
> Put preprocessors in all library stansas in same file

- bin/Pesy.re
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-lwt-sample/package.json
- lib/PesyConf.re
- npm-cli/package-lock.json
- npm-cli/package.json
> Address feedback  

- npm-cli/scripts/vendor-template.js
- npm-cli/src/Bindings.bs.js
- npm-cli/src/Bindings.re
- npm-cli/src/Pesy.bs.js
- npm-cli/src/Pesy.re
- npm-cli/src/Spinner.bs.js
- npm-cli/src/Spinner.re
- npm-cli/src/Utils.bs.js
- npm-cli/src/Utils.re
Fixes failing `esy start` and `esy test` in the bootstrapped template
> Fix buggy template

- esy.lock/index.json
- npm-cli/esy.json
- npm-cli/esy.lock/.gitattributes
- npm-cli/esy.lock/.gitignore
- npm-cli/esy.lock/index.json
- npm-cli/esy.lock/opam/base-threads.base/opam
- npm-cli/esy.lock/opam/base-unix.base/opam
- npm-cli/esy.lock/opam/biniou.1.2.1/opam
- npm-cli/esy.lock/opam/conf-m4.1/opam
- npm-cli/esy.lock/opam/cppo.1.6.6/opam
- npm-cli/esy.lock/opam/dune.2.0.1/opam
- npm-cli/esy.lock/opam/easy-format.1.3.2/opam
- npm-cli/esy.lock/opam/menhir.20190924/opam
- npm-cli/esy.lock/opam/merlin-extend.0.5/opam
- npm-cli/esy.lock/opam/ocaml-migrate-parsetree.1.5.0/opam
- npm-cli/esy.lock/opam/ocamlbuild.0.14.0/opam
- npm-cli/esy.lock/opam/ocamlfind.1.8.1/files/ocaml-stub
- npm-cli/esy.lock/opam/ocamlfind.1.8.1/files/ocamlfind.install
- npm-cli/esy.lock/opam/ocamlfind.1.8.1/opam
- npm-cli/esy.lock/opam/ppx_derivers.1.2.1/opam
- npm-cli/esy.lock/opam/ppx_yojson_conv_lib.v0.13.0/opam
- npm-cli/esy.lock/opam/result.1.4/opam
- npm-cli/esy.lock/opam/yojson.1.7.0/opam
- npm-cli/esy.lock/overrides/opam__s__ocamlbuild_opam__c__0.14.0_opam_override/files/ocamlbuild-0.14.0.patch
- npm-cli/esy.lock/overrides/opam__s__ocamlbuild_opam__c__0.14.0_opam_override/package.json
- npm-cli/esy.lock/overrides/opam__s__ocamlfind_opam__c__1.8.1_opam_override/files/findlib-1.8.1.patch
- npm-cli/esy.lock/overrides/opam__s__ocamlfind_opam__c__1.8.1_opam_override/package.json
* Updates root lock files
* Add esy.json to bucklescript part for editor tools
> Update lock files

- bin/Pesy.re
- e2e-tests/Runner.re
- npm-cli/package-lock.json
- npm-cli/package.json
- npm-cli/src/Pesy.bs.js
- npm-cli/src/Pesy.re
- package.json
- pesy--esy-pesy.opam
- scripts/run.bat
- scripts/run.sh
pesy: 0.5.0-alpha.11
esy-pesy: 0.1.0-alpha.5
> Bump pesy and esy-pesy versions

- npm-cli/package.json
- npm-cli/rollup.config.js
- npm-cli/yarn.lock
https://github.com/esy/pesy/network/alert/npm-cli/yarn.lock/minimist/open
> Bump npm deps to address the minimist issue

- npm-cli/bsconfig.json
- npm-cli/package.json
- npm-cli/rollup.config.js
- npm-cli/src/AzurePipelines.re
- npm-cli/src/Bindings.re
- npm-cli/src/Cmd.re
- npm-cli/src/Pesy.re
- npm-cli/src/Readline.re
- npm-cli/src/Utils.re
- npm-cli/src/Warmup.re
- npm-cli/stubs/fs.js
- npm-cli/yarn.lock
Hyrdates esy store with prebuilts from the CI
> Adds 'pesy warm' command

- npm-cli/src/Pesy.re
Bootstrapper was incorrectly setting the cwd. This commit fixes it
> Fixes --init option

- npm-cli/src/Cmd.re
Bucklescript had evaluated it at compile time
> Lazy env_sep

- npm-cli/esy.json
- npm-cli/esy.lock/index.json
- npm-cli/esy.lock/opam/ocaml-migrate-parsetree.1.7.3/opam
- npm-cli/esy.lock/opam/ocaml-syntax-shims.1.0.0/opam
- npm-cli/src/AzurePipelines.re
- npm-cli/src/Bindings.re
- npm-cli/src/PesyConfig.re
- npm-cli/src/PesyConfig.rei
- npm-cli/src/Warmup.re
Some times, an Azure Pipeline project may have multiple piplines running
> Look up correct build ID using github repository name

- .ci/esy-build-steps.yml
- .ci/utils/use-cache-yarn.yml
- npm-cli/scripts/vendor-template.js
- npm-cli/src/DefaultTemplate.re
> Update bootstrapper template

- lib/PesyConf.re
- unit-tests/runner/Lib.re
@ManasJayanth this PR Fixes #18
Please review this, help me out If am missing out on any convension/best-practice
> Adds support for flags as string

- lib/Executable.re
- lib/Executable.rei
- lib/PesyConf.re
- unit-tests/runner/Lib.re
> Adds better support for executable modes

- npm-cli/templates/ci/.ci/build-platform.yml
A recent fix in esy updates the length to 85
> Update store path length to 85

- lib/PesyConf.re
- lib/PesyModule.re
> skip module aliasing if same namespace

- bin/Pesy.re
- errors/Errors.re
- lib/Lib.re
- lib/PesyConf.re
> Fix misleading error message when local library not found

- lib/PesyConf.re
Previously, we only looked for native libraries
> Fix Findlib lookup to include bytecode libs/namespaces

- lib/Executable.re
If an executable mode contains, public_name(s), Dune thinks, it's either,
- exe
- native
- byte
```
1 | (executables (names TestProjectApp)
2 |     (modules (:standard \ TestProjectSrcBinPesyModules))
3 |     (public_names TestProjectApp) (libraries TestProjectSrcBinPesyModules)
4 |     (modes js) (flags -open TestProjectSrcBinPesyModules)
5 |     (preprocess (pps js_of_ocaml-ppx)))
Error: No installable mode found for these executables.
When public_name is set, one of the following modes is required:
- exe
- native
- byte
```
This commits skips emitting public_names if the `modes` field is set to JS
> Skip emitting public_names when executable mode is js
