esy/pesy

- assets/pesy-Test.template.re
- assets/pesy-package.template.json
This is the smallest thing possible that I could come up with.
In a real world scenario we probably want to break out the `TestFramework` module to its own file. We probably also want to have a `link-all` flag possible so that each test can be in its own file without getting optimised away.
> Add rely tests to template

- esy.lock/index.json
- esy.lock/opam/ocamlfind.1.8.0/opam
- package.json
pesy will be needed only during development. And dune files
will be committed. Pesy doesn't need to be pinned to github
> Remove pesy-self. Since pesy is a dev dependency

- assets/dune
- assets/pesy-RunTests.template.re
- assets/pesy-Test.template.re
- assets/pesy-TestFramework.template.re
- assets/pesy-package.template.json
- lib/Lib.re
- lib/PesyConf.re
This separates the current Test.re file into three separate files and the current test project into a library and an executable so that the linkall flag can be used to improve developer experience when it comes to associating tests with the framework. Additionally I changed Pesy to no longer use the Test stanza/dune runtest due to the output swallowing behavior.
It looks like .re files written from the templates have a leading blank newline, however this was not introduced by my change (I verified that this happened with current master as well).
I tested this by running:
```
npm pack
tar -zxvf pesy-whatever
cd package
esy install
esy x (which pesy)
```
and then using the location from the esy x command to install a new project.
Currently when running this against an existing project it …
> Update Rely Setup

- assets/azure-pipeline-templates/pesy-esy-build-steps.template.yml
A few esy versions back we some issue with installing assets inside the sandbox because of which we had to create a separate binary called pesy-configure. This is not necessary anymore.
Addresses #24
> Update CI template

- assets/pesy-package.template.json
- esy.lock/.gitattributes
- esy.lock/index.json
- esy.lock/opam/conf-m4.1/opam
- esy.lock/opam/conf-which.1/opam
- esy.lock/opam/menhir.20190626/opam
- esy.lock/opam/ocaml-migrate-parsetree.1.4.0/opam
- package.json
See https://github.com/jchavarri/rebez/issues/4
"This is probably due to stale dune files: pesy must have marked dune files as stale after it updated. But the problem can be avoided by using pesy a bit differently.
Pesy is right now caught in between being a build tool and a config manager. It doesn't function to it full potential as a build tool as it doesn't work closely with dune enough (for instance it is forced to create dune files in source). So it's best left to just manage config for you.
This means, we now use pesy only to generated config files for the project (dune and CI). We can now move pesy to devDependencies, thereby ensuring packages that consume rebez don't have to pull pesy."
> Use pesy as a dev dependency

- npm-cli/share/template-repo/pesy-package.template.json
When creating a new project it's not possible to run the `rely` tests because we're not destructuring and using all the record fields.
This PR adds the flag to ignore that issue.
> Ignore destructuring warning in tests

- npm-cli/src/Spinner.re
'Fetching github repo' is a long log statement. Its / character is
farthest away. When the progress indicator is rendered again, it
doesn't get cleared
You may now run 'esy test'                          -
> More padding for longer logs

- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/.gitignore
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/dune
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/dune-project
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/executable/PesyNpmApp.re
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/lib_foo/Util.re
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/lib_foo/foo/bar/Index.re
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/package.json
- e2e-tests/pesy-configure-test-projects/pesy-npm-with-underscore/test/TestPesyNpm.re
- lib/Lexer.mll
As reported by @ulrikstrid , the following config would fail
```json
"buildDirs": {
"test": {
"imports": [
"Library = require('morph_template/library')",
"Rely = require('rely/lib')"
],
"flags": [
"-linkall",
"-g",
"-w",
"-9"
]
},
"testExe": {
"imports": [
"Test = require('morph_template/test')"
],
"bin": {
"RunMorph_templateTests.exe": "RunMorph_templateTests.re"
}
},
"library": {
"imports": [
"Opium_core = require('opium_core')",
"Morph = require('morph')",
"Mtime = require('mtime')",
"Mtime_clock = require('mtime.clock.os')",
"Logs = require('logs')",
"Lwt = require('lwt')"
]
},
"bin": {
"imports": [
"Library = require('morph_template/library')",
"Morph = require('morph')",
"Morph_server_http = require('morph_server_http')",
"Logs = require('logs')",
"Logs_fmt = require('logs.fmt')", …
```
> Accept underscores in module path

- npm-cli/rollup.config.js
- npm-cli/src/Bindings.re
- npm-cli/src/Pesy.bs.js
- npm-cli/src/Pesy.re
> Use path.basename (nodejs) instead of Filename.basename (ocaml stdlib)

- npm-cli/src/Pesy.bs.js
- npm-cli/src/Pesy.re
My attempt to add a `-y/--yes` flag to use default options.
It currently only bypasses the check for the empty directory but I guess in the future we could use it for other things.
> Add -y/--yes option

- bin/Pesy.re
This removes the need for knowing the sandbox name during `esy status`
> Multisandbox fix: Use ESY__ROOT_PACKAGE_CONFIG_PATH from env

- lib/Lexer.mll
MODULE_NAME:
https://caml.inria.fr/pub/docs/manual-ocaml/lex.html#capitalized-identa
MODULE_PATH: Could be any valid unix path. Which means it could be any
non null character? In real-world it need not be that flexible - for
Windows compatibility we'll have to restrict the following
> MS-DOS, Microsoft Windows, and OS/2 disallow the characters \ / :
> ? * " > < | and NUL in file and directory names across all
> filesystems. Unices and Linux disallow the characters / and NUL in
> file and directory names across all filesystems.
Refer: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits
And
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5,
COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4,
LPT5, LPT6, LPT7, LPT8, LPT9
Refer: http://msdn.microsoft.com/en-us/library/aa365247.aspx …
> Fix regexp for MODULE_NAME and MODULE_PATH

- lib/Executable.re
- lib/Library.re
- lib/Test.re
- lib/UnitTests.re
This addresses the generation of the `include_subdirs` stanza that was included in the library/executable/test stanza.
> Fixes include_subdirs stanza generation

- .ci/build-platform.yml
- azure-pipelines.yml
- npm-cli/v0.4.4/azure-ci-template/azure-pipelines.yml
Replaced all `macos-10.13` to `latest` version.
See: https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/
I'm not sure though that it was required in the `npm-cli/v0.4.4` folder?
> CI: Use macos-latest

- npm-cli/src/Pesy.re
This should bring down the number of rename operations (and there points of failure on Windows)
> Avoid unnecessary renames

- .ci/build-platform.yml
- e2e-tests/Runner.re
- lib/Lib.re
- lib/PesyConf.re
- utils/Utils.re
We only support direct import of libraries only when they were written with pesy or following pesy convention. Example: @foo/bar library was expected to have it's opam file by the name foo--bar and it's respective sub-libraries as foo-bar.baz etc. Although extremely useful to follow such conventions (particularly wrt namespacing on NPM), it limited imports to work only with other libraries that were written with pesy.
This PR makes no such assumption and uses findlib to lookup the correct library name and enables use of existing libraries with pesy that need not follow pesy conventions or have used pesy to publish them.
Example import statement
```json
"imports": [ "Console = require('@reason-native/console/lib')" ]
```
> Better support for namespaced NPM dependencies

- README.html
The bracket was in a place where it appeared that both `esy pesy` 
and `esy @mysandbox pesy` were for sandbox usage but if I understand
correctly, that's not the case. Moving the bracket makes that clearer.
> Fix bracket for sandbox command

- lib/PesyConf.re
Issue: pesy incorrectly showed @opam/result and @opam/re
for @opam/re as candidates
> Resolve ambiguities for multiple candidates

- bin/Pesy.re
- e2e-tests/Runner.re
- npm-cli/package.json
- npm-cli/src/Pesy.re
- package.json
- scripts/run.bat
- scripts/run.sh
TODO: Add a convenient alternative to `git ls-files | xargs sed -i 's/alpha.22/dev.23/g'` to make such string replacements
`dune substs` doesn't work for us since those edits are in-source and we cant check into `%{VERSION}` into the git repository. (Atleast not for now)
> Use dev version

- npm-cli/src/Utils.re
Issue: Entering invalid input shows the prompt again but since the previous interface was not closed, it prints any key you type, twice.
Solution: Close the readline interface
> Closes readline interface on invalid inputs

- e2e-tests/Runner.re
- lib/Common.re
- lib/Library.re
- lib/Library.rei
- lib/PesyConf.re
- lib/PesyModule.re
- unit-tests/runner/Lib.re
We have been incorrectly making every sub-library public - causing Dune to unnecessarily create plugins, shared objects etc. Not all folders in a package need to be publicly available.
This PR adds support for a `public` field in a library, that would make it public, ie available as a findlib library.
> Explicitly make a sublibrary public with "public" field
